<h1>Listar Usuarios</h1>
<br/>
<br/>
<div>
<!--    <a class="btn btn-success" href="<? =$this->basePath()?>application/index/add">Añadir usuario</a>-->
    <a class="btn btn-success" href="<?=$this->basePath("rutauno")?>">Añadir Usuario</a>
</div>
<br/>
<table border="1">
    <tr>
        <th>Nombre</th>
        <th>Apellido</th>
        <th>Direccion</th>
        <th>Telefono</th>
        <th>Estado</th>
        <th style="text-align: center">Ver</th>
        <th style="text-align: center">Modificar</th>
        <th style="text-align: center">Eliminar</th>
    </tr>
    <?php foreach ($this->lista as $last){;?>
    <?php 
        if($last['estado']=='1') $estado = "Activo";
        else $estado = "Inactivo";  
    ?>
    <tr>
    <td> <?php echo  $last['nombre'];?></td>
    <td> <?php echo  $last['apellido'];?></td>
    <td> <?php echo  $last['direccion'];?></td>
    <td> <?php echo  $last['telefono'];?></td>
    <td> <?php echo  $estado;?></td>
    <td>
        <a class="btn btn-success" href="<?=$this->basePath()?>/application/index/ver/<?=$last["idusuarios"]?>">Ver</a>
    </td>
    <td>
        <a class="btn btn-primary" href="<?=$this->basePath()?>/application/index/modificar/<?=$last["idusuarios"]?>">Modificar</a>
    </td>
    <td>
        <a class="btn btn-danger" href="<?=$this->basePath()?>/application/index/eliminar/<?=$last["idusuarios"]?>">Eliminar</a>
    </td>
    </tr>
    <?php };?>
    
   
</table>

